spring.application.name=ThirdYear

spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=root
spring.datasource.password=kiak5296$$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true